name: Continuous Integration
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: python3 -m unittest object_analysis_tests.py